url: "https://icse-tamil-translations.github.io" # the base hostname & protocol for your site
title: ICSE Tamil Translations # Default page title

google_analytics: G-KR3YLZK4DZ # Google analytics tracking ID

plugins: # Custom Rubygems for Jekyll
  - jekyll-sitemap